# **E-Commerce Data Analysis**

---

The objective of this project is to analyze e-commerce sales data to gain insights into customer behavior, sales trends, and overall business performance. The analysis helps identify profitable categories and brands, understand sales patterns over time, and support data-driven business decisions.

**Data Loading and Initial Overview**

In this section, the dataset is downloaded directly from Google Drive using the gdown library and loaded into a Pandas DataFrame. An initial exploration is performed to understand the structure of the dataset, including the number of rows and columns, data types, and a preview of the first few records. Summary statistics are generated to understand numerical distributions, while dataset information helps identify missing values and inconsistencies.

Purpose:

*   Understand dataset size and structure
*   Identify data types and potential quality issues
*   Get a high-level understanding of the data

In [ ]:
import gdown

file_id = "1fbCVtM8KKpRgFxlASWnG0ERBXEIQIzHt"
url = f"https://drive.google.com/uc?id={file_id}"

output = "Online-eCommerce.csv"
gdown.download(url, output, quiet=False)

print("\nDownloaded file:", output)

Downloading...
From: https://drive.google.com/uc?id=1fbCVtM8KKpRgFxlASWnG0ERBXEIQIzHt
To: /content/Online-eCommerce.csv
100%|██████████| 566k/566k [00:00<00:00, 19.1MB/s]

Downloaded file: Online-eCommerce.csv

In [ ]:
import pandas as pd

df = pd.read_csv("Online-eCommerce.csv", low_memory=False)
print(df.head())

   Order_Number State_Code   Customer_Name  Order_Date     Status  \
0      139374.0         AP     Adhir Samal  11/01/2020  Delivered
1      139375.0         AP  Dannana Jhammi  11/01/2020  Delivered
2      139376.0         AS     Vipin Kumar  11/01/2020  Delivered
3      139377.0         BR   Ranjeet Kumar  11/01/2020  Delivered
4      139378.0         CG   Sajal Singhal  11/01/2020      Order

                    Product      Category     Brand    Cost    Sales  \
0                512 GB M.2           SSD   Samsung  6500.0   8450.0
1      RYZEN 3rd gen. 3500            CPU     Intel  8500.0  11050.0
2          2GB Graphic Card  Graphic Card    Nvidia  7000.0   9100.0
3            16 GB DDR4 RAM           RAM     Hynix  6550.0   8515.0
4  Standard ATX motherboard   MotherBoard  Gigabyte  7650.0   9945.0

   Quantity  Total_Cost  Total_Sales Assigned Supervisor
0       1.0      6500.0       8450.0         Ajay Sharma
1       3.0     25500.0      33150.0        Roshan Kumar
2       2.0     14000.0      18200.0         Aarvi Gupta
3       3.0     19650.0      25545.0         Vijay Singh
4       4.0     30600.0      39780.0          Aadil Khan

In [ ]:
# Number of columns and rows
rows, cols = df.shape
print("Number of Rows:", rows)
print("Number of Columns:", cols)

Number of Rows: 5110
Number of Columns: 14

In [ ]:
# column data types
df.dtypes

Order_Number           float64
State_Code              object
Customer_Name           object
Order_Date              object
Status                  object
Product                 object
Category                object
Brand                   object
Cost                   float64
Sales                  float64
Quantity               float64
Total_Cost             float64
Total_Sales            float64
Assigned Supervisor     object
dtype: object

In [ ]:
# First rows
display(df.head(10))

# Detailed dataset info
df.info()

# Summary statistics (numeric only)
df.describe()

# Summary for all columns (numeric + categorical)
df.describe(include='all')

,Order_Number,State_Code,Customer_Name,Order_Date,Status,Product,Category,Brand,Cost,Sales,Quantity,Total_Cost,Total_Sales,Assigned Supervisor
0,139374.0,AP,Adhir Samal,11/01/2020,Delivered,512 GB M.2,SSD,Samsung,6500.0,8450.0,1.0,6500.0,8450.0,Ajay Sharma
1,139375.0,AP,Dannana Jhammi,11/01/2020,Delivered,RYZEN 3rd gen. 3500,CPU,Intel,8500.0,11050.0,3.0,25500.0,33150.0,Roshan Kumar
2,139376.0,AS,Vipin Kumar,11/01/2020,Delivered,2GB Graphic Card,Graphic Card,Nvidia,7000.0,9100.0,2.0,14000.0,18200.0,Aarvi Gupta
3,139377.0,BR,Ranjeet Kumar,11/01/2020,Delivered,16 GB DDR4 RAM,RAM,Hynix,6550.0,8515.0,3.0,19650.0,25545.0,Vijay Singh
4,139378.0,CG,Sajal Singhal,11/01/2020,Order,Standard ATX motherboard,MotherBoard,Gigabyte,7650.0,9945.0,4.0,30600.0,39780.0,Aadil Khan
5,139379.0,CG,Akhilesh Kumar,11/01/2020,Order,Compact with 1 Fan,Cabinet,Asus,1150.0,1495.0,2.0,2300.0,2990.0,Advika Joshi
6,139380.0,CG,Suvankar Chakraborty,11/01/2020,Order,USB Backlight Keyboard,Keyboard,Dell,850.0,1105.0,3.0,2550.0,3315.0,Ajay Sharma
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,139381.0,CG,Suvankar Adhikary,12/01/2020,Order,Ergonomic Mouse,Mouse,Samsung,650.0,845.0,2.0,1300.0,1690.0,Ajay Sharma

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Order_Number         5095 non-null   float64
 1   State_Code           5095 non-null   object
 2   Customer_Name        5095 non-null   object
 3   Order_Date           5095 non-null   object
 4   Status               5095 non-null   object
 5   Product              5095 non-null   object
 6   Category             5095 non-null   object
 7   Brand                5095 non-null   object
 8   Cost                 5095 non-null   float64
 9   Sales                5095 non-null   float64
 10  Quantity             5095 non-null   float64
 11  Total_Cost           5095 non-null   float64
 12  Total_Sales          5095 non-null   float64
 13  Assigned Supervisor  5095 non-null   object
dtypes: float64(6), object(8)
memory usage: 559.0+ KB

,Order_Number,State_Code,Customer_Name,Order_Date,Status,Product,Category,Brand,Cost,Sales,Quantity,Total_Cost,Total_Sales,Assigned Supervisor
count,5095.000000,5095,5095,5095,5095,5095,5095,5095,5095.000000,5095.000000,5095.000000,5095.000000,5095.000000,5095
unique,NaN,35,56,1086,4,1228,14,11,NaN,NaN,NaN,NaN,NaN,6
top,NaN,MH,Adhir Samal,03/04/2022,Processing,2GB Graphic Card,Monitor,Samsung,NaN,NaN,NaN,NaN,NaN,Aarvi Gupta
freq,NaN,904,122,181,1278,300,749,1199,NaN,NaN,NaN,NaN,NaN,967
mean,141921.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6066.123651,7885.960746,2.486948,14991.778214,19489.311678,NaN
std,1470.944141,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3952.022039,5137.628651,1.113581,12574.918427,16347.393955,NaN
min,139374.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,350.000000,455.000000,1.000000,350.000000,455.000000,NaN
25%,140647.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2100.000000,2730.000000,2.000000,4500.000000,5850.000000,NaN
50%,141921.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6550.000000,8515.000000,2.000000,10720.000000,13936.000000,NaN
75%,143194.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8500.000000,11050.000000,3.000000,22950.000000,29835.000000,NaN
max,144468.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14500.000000,18850.000000,4.000000,58000.000000,75400.000000,NaN

**Data Pre-processing**

Data pre-processing focuses on cleaning and preparing the dataset for analysis. Missing values are identified and handled appropriately numerical columns are filled with median values, while categorical columns are filled with mode values. Duplicate records are removed to avoid biased analysis. Data types are corrected for categorical fields, and new derived columns such as Profit and Profit Margin are created. Date fields are cleaned, converted into proper datetime format, and additional time-based features are extracted.

Purpose:

*   Improve data quality and consistency
*  Handle missing and duplicate records
*   Create meaningful derived features for analysis

In [ ]:
# Missing values count & percent
missing = df.isnull().sum()
missing_pct = (missing / len(df)) * 100

missing_df = pd.DataFrame({
    "Missing Count": missing,
    "Missing %": missing_pct.round(2)
})

missing_df.sort_values("Missing Count", ascending=False)

                     Missing Count  Missing %
Order_Number                    15       0.29
State_Code                      15       0.29
Customer_Name                   15       0.29
Order_Date                      15       0.29
Status                          15       0.29
Product                         15       0.29
Category                        15       0.29
Brand                           15       0.29
Cost                            15       0.29
Sales                           15       0.29
Quantity                        15       0.29
Total_Cost                      15       0.29
Total_Sales                     15       0.29
Assigned Supervisor             15       0.29

In [ ]:
# Handling Missing Values
# Fill missing numeric values with median
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

# Fill missing text/categorical with mode
categorical_cols = df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

# Removing Duplicates
# Count duplicates
print("Duplicate Rows:", df.duplicated().sum())

# Drop duplicates
df = df.drop_duplicates().reset_index(drop=True)

print("After removing duplicates:", df.shape)

print(df)

Duplicate Rows: 14
After removing duplicates: (5096, 14)
      Order_Number State_Code          Customer_Name  Order_Date      Status  \
0         139374.0         AP            Adhir Samal  11/01/2020   Delivered
1         139375.0         AP         Dannana Jhammi  11/01/2020   Delivered
2         139376.0         AS            Vipin Kumar  11/01/2020   Delivered
3         139377.0         BR          Ranjeet Kumar  11/01/2020   Delivered
4         139378.0         CG          Sajal Singhal  11/01/2020       Order
...            ...        ...                    ...         ...         ...
5091      144464.0         TN  Rahul Kumar Prajapati  31/12/2022   Delivered
5092      144465.0         TR             Sagar Jeur  31/12/2022     Shipped
5093      144466.0         UK        Rhushikesh Mane  31/12/2022       Order
5094      144467.0         UP           Ashish Kumar  31/12/2022  Processing
5095      144468.0         WB           Javed Akhter  31/12/2022   Delivered

                       Product      Category     Brand     Cost    Sales  \
0                   512 GB M.2           SSD   Samsung   6500.0   8450.0
1         RYZEN 3rd gen. 3500            CPU     Intel   8500.0  11050.0
2             2GB Graphic Card  Graphic Card    Nvidia   7000.0   9100.0
3               16 GB DDR4 RAM           RAM     Hynix   6550.0   8515.0
4     Standard ATX motherboard   MotherBoard  Gigabyte   7650.0   9945.0
...                        ...           ...       ...      ...      ...
5091                406 GB SSD           SSD   Samsung   4500.0   5850.0
5092        Intel i3 11th gen.           CPU     Intel   8500.0  11050.0
5093          4GB Graphic card  Graphic Card    Nvidia  12500.0  16250.0
5094           158 GB DDR4 RAM           RAM     Hynix   3500.0   4550.0
5095           BTX motherboard   Motherboard  Gigabyte   4500.0   5850.0

      Quantity  Total_Cost  Total_Sales Assigned Supervisor
0          1.0      6500.0       8450.0         Ajay Sharma
1          3.0     25500.0      33150.0        Roshan Kumar
2          2.0     14000.0      18200.0         Aarvi Gupta
3          3.0     19650.0      25545.0         Vijay Singh
4          4.0     30600.0      39780.0          Aadil Khan
...        ...         ...          ...                 ...
5091       1.0      4500.0       5850.0         Ajay Sharma
5092       4.0     34000.0      44200.0        Roshan Kumar
5093       2.0     25000.0      32500.0         Aarvi Gupta
5094       2.0      7000.0       9100.0         Vijay Singh
5095       3.0     13500.0      17550.0          Aadil Khan

[5096 rows x 14 columns]

In [ ]:
# Correcting Data Types
cat_cols = ['State_Code', 'Category', 'Brand', 'Status']

for col in cat_cols:
    if col in df.columns:
        df[col] = df[col].astype('category')

print(df)

      Order_Number State_Code          Customer_Name  Order_Date      Status  \
0         139374.0         AP            Adhir Samal  11/01/2020   Delivered
1         139375.0         AP         Dannana Jhammi  11/01/2020   Delivered
2         139376.0         AS            Vipin Kumar  11/01/2020   Delivered
3         139377.0         BR          Ranjeet Kumar  11/01/2020   Delivered
4         139378.0         CG          Sajal Singhal  11/01/2020       Order
...            ...        ...                    ...         ...         ...
5091      144464.0         TN  Rahul Kumar Prajapati  31/12/2022   Delivered
5092      144465.0         TR             Sagar Jeur  31/12/2022     Shipped
5093      144466.0         UK        Rhushikesh Mane  31/12/2022       Order
5094      144467.0         UP           Ashish Kumar  31/12/2022  Processing
5095      144468.0         WB           Javed Akhter  31/12/2022   Delivered

                       Product      Category     Brand     Cost    Sales  \
0                   512 GB M.2           SSD   Samsung   6500.0   8450.0
1         RYZEN 3rd gen. 3500            CPU     Intel   8500.0  11050.0
2             2GB Graphic Card  Graphic Card    Nvidia   7000.0   9100.0
3               16 GB DDR4 RAM           RAM     Hynix   6550.0   8515.0
4     Standard ATX motherboard   MotherBoard  Gigabyte   7650.0   9945.0
...                        ...           ...       ...      ...      ...
5091                406 GB SSD           SSD   Samsung   4500.0   5850.0
5092        Intel i3 11th gen.           CPU     Intel   8500.0  11050.0
5093          4GB Graphic card  Graphic Card    Nvidia  12500.0  16250.0
5094           158 GB DDR4 RAM           RAM     Hynix   3500.0   4550.0
5095           BTX motherboard   Motherboard  Gigabyte   4500.0   5850.0

      Quantity  Total_Cost  Total_Sales Assigned Supervisor
0          1.0      6500.0       8450.0         Ajay Sharma
1          3.0     25500.0      33150.0        Roshan Kumar
2          2.0     14000.0      18200.0         Aarvi Gupta
3          3.0     19650.0      25545.0         Vijay Singh
4          4.0     30600.0      39780.0          Aadil Khan
...        ...         ...          ...                 ...
5091       1.0      4500.0       5850.0         Ajay Sharma
5092       4.0     34000.0      44200.0        Roshan Kumar
5093       2.0     25000.0      32500.0         Aarvi Gupta
5094       2.0      7000.0       9100.0         Vijay Singh
5095       3.0     13500.0      17550.0          Aadil Khan

[5096 rows x 14 columns]

Additional useful columns are created to enhance analysis. These include profit-related metrics and date-based features such as year, month, day, and year-month. These derived features allow deeper time-series and performance analysis across different periods.

Purpose:

*   Enable time-based trend analysis
*   Improve analytical depth
*   Support aggregation and comparison

In [ ]:
# Creating derived columns
# Profit
if all(c in df.columns for c in ['Total_Sales', 'Total_Cost']):
    df['Profit'] = df['Total_Sales'] - df['Total_Cost']

# Profit Margin
if 'Profit' in df.columns and 'Total_Sales' in df.columns:
    df['Profit_Margin'] = (df['Profit'] / df['Total_Sales']).round(2)

print(df)

      Order_Number State_Code          Customer_Name  Order_Date      Status  \
0         139374.0         AP            Adhir Samal  11/01/2020   Delivered
1         139375.0         AP         Dannana Jhammi  11/01/2020   Delivered
2         139376.0         AS            Vipin Kumar  11/01/2020   Delivered
3         139377.0         BR          Ranjeet Kumar  11/01/2020   Delivered
4         139378.0         CG          Sajal Singhal  11/01/2020       Order
...            ...        ...                    ...         ...         ...
5091      144464.0         TN  Rahul Kumar Prajapati  31/12/2022   Delivered
5092      144465.0         TR             Sagar Jeur  31/12/2022     Shipped
5093      144466.0         UK        Rhushikesh Mane  31/12/2022       Order
5094      144467.0         UP           Ashish Kumar  31/12/2022  Processing
5095      144468.0         WB           Javed Akhter  31/12/2022   Delivered

                       Product      Category     Brand     Cost    Sales  \
0                   512 GB M.2           SSD   Samsung   6500.0   8450.0
1         RYZEN 3rd gen. 3500            CPU     Intel   8500.0  11050.0
2             2GB Graphic Card  Graphic Card    Nvidia   7000.0   9100.0
3               16 GB DDR4 RAM           RAM     Hynix   6550.0   8515.0
4     Standard ATX motherboard   MotherBoard  Gigabyte   7650.0   9945.0
...                        ...           ...       ...      ...      ...
5091                406 GB SSD           SSD   Samsung   4500.0   5850.0
5092        Intel i3 11th gen.           CPU     Intel   8500.0  11050.0
5093          4GB Graphic card  Graphic Card    Nvidia  12500.0  16250.0
5094           158 GB DDR4 RAM           RAM     Hynix   3500.0   4550.0
5095           BTX motherboard   Motherboard  Gigabyte   4500.0   5850.0

      Quantity  Total_Cost  Total_Sales Assigned Supervisor   Profit  \
0          1.0      6500.0       8450.0         Ajay Sharma   1950.0
1          3.0     25500.0      33150.0        Roshan Kumar   7650.0
2          2.0     14000.0      18200.0         Aarvi Gupta   4200.0
3          3.0     19650.0      25545.0         Vijay Singh   5895.0
4          4.0     30600.0      39780.0          Aadil Khan   9180.0
...        ...         ...          ...                 ...      ...
5091       1.0      4500.0       5850.0         Ajay Sharma   1350.0
5092       4.0     34000.0      44200.0        Roshan Kumar  10200.0
5093       2.0     25000.0      32500.0         Aarvi Gupta   7500.0
5094       2.0      7000.0       9100.0         Vijay Singh   2100.0
5095       3.0     13500.0      17550.0          Aadil Khan   4050.0

      Profit_Margin
0              0.23
1              0.23
2              0.23
3              0.23
4              0.23
...             ...
5091           0.23
5092           0.23
5093           0.23
5094           0.23
5095           0.23

[5096 rows x 16 columns]

In [ ]:
# Date Correction
df['Order_Date'] = df['Order_Date'].astype(str).str.strip()

# Auto parse dates
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')

mask_na = df['Order_Date'].isna()
if mask_na.sum() > 0:
    df.loc[mask_na, 'Order_Date'] = pd.to_datetime(
        df.loc[mask_na, 'Order_Date'],
        errors='coerce',
        dayfirst=True
    )

print("\nAfter correction:")
print(df['Order_Date'].head(20))
print(df['Order_Date'].isna().sum(), "dates could not be converted.")

# Create useful derived date columns
df['Order_Year'] = df['Order_Date'].dt.year
df['Order_Month'] = df['Order_Date'].dt.month
df['Order_Day'] = df['Order_Date'].dt.day
df['Order_Month_Name'] = df['Order_Date'].dt.strftime('%B')
df['Year_Month'] = df['Order_Date'].dt.to_period('M').astype(str)
df = df.dropna(subset=['Order_Date']).reset_index(drop=True)

print("\nDate correction completed successfully!")

After correction:
0    2020-11-01
1    2020-11-01
2    2020-11-01
3    2020-11-01
4    2020-11-01
5    2020-11-01
6    2020-11-01
7    2020-03-04
8    2020-12-01
9           NaT
10          NaT
11          NaT
12          NaT
13          NaT
14          NaT
15          NaT
16          NaT
17          NaT
18          NaT
19          NaT
Name: Order_Date, dtype: datetime64[ns]
3056 dates could not be converted.

Date correction completed successfully!

In [ ]:
print(df)

      Order_Number State_Code        Customer_Name Order_Date      Status  \
0         139374.0         AP          Adhir Samal 2020-11-01   Delivered
1         139375.0         AP       Dannana Jhammi 2020-11-01   Delivered
2         139376.0         AS          Vipin Kumar 2020-11-01   Delivered
3         139377.0         BR        Ranjeet Kumar 2020-11-01   Delivered
4         139378.0         CG        Sajal Singhal 2020-11-01       Order
...            ...        ...                  ...        ...         ...
2035      144321.0         TN   Aniruddha Kekapure 2022-10-12     Shipped
2036      144322.0         TR           Aslam Raza 2022-10-12       Order
2037      144323.0         MH        Roshan Zameer 2022-10-12  Processing
2038      144324.0         CH  Rakesh Kumar Sharma 2022-11-12   Delivered
2039      144325.0         DH     Shivanand Sahani 2022-12-12     Shipped

                         Product      Category     Brand     Cost    Sales  \
0                     512 GB M.2           SSD   Samsung   6500.0   8450.0
1           RYZEN 3rd gen. 3500            CPU     Intel   8500.0  11050.0
2               2GB Graphic Card  Graphic Card    Nvidia   7000.0   9100.0
3                 16 GB DDR4 RAM           RAM     Hynix   6550.0   8515.0
4       Standard ATX motherboard   MotherBoard  Gigabyte   7650.0   9945.0
...                          ...           ...       ...      ...      ...
2035             153 GB DDR4 RAM           RAM   Samsung   2650.0   3445.0
2036             26" LCD Display       Monitor      Acer  12550.0  16315.0
2037  I7 - intel 12th Generation           CPU     Intel  14500.0  18850.0
2038                USB Keyboard      Keyboard      Dell    800.0   1040.0
2039              Wireless Mouse         Mouse   Samsung    600.0    780.0

      ...  Total_Cost  Total_Sales  Assigned Supervisor   Profit  \
0     ...      6500.0       8450.0          Ajay Sharma   1950.0
1     ...     25500.0      33150.0         Roshan Kumar   7650.0
2     ...     14000.0      18200.0          Aarvi Gupta   4200.0
3     ...     19650.0      25545.0          Vijay Singh   5895.0
4     ...     30600.0      39780.0           Aadil Khan   9180.0
...   ...         ...          ...                  ...      ...
2035  ...      7950.0      10335.0         Roshan Kumar   2385.0
2036  ...     37650.0      48945.0          Aarvi Gupta  11295.0
2037  ...     14500.0      18850.0          Vijay Singh   4350.0
2038  ...      1600.0       2080.0           Aadil Khan    480.0
2039  ...      1800.0       2340.0         Advika Joshi    540.0

      Profit_Margin  Order_Year  Order_Month  Order_Day  Order_Month_Name  \
0              0.23      2020.0         11.0        1.0          November
1              0.23      2020.0         11.0        1.0          November
2              0.23      2020.0         11.0        1.0          November
3              0.23      2020.0         11.0        1.0          November
4              0.23      2020.0         11.0        1.0          November
...             ...         ...          ...        ...               ...
2035           0.23      2022.0         10.0       12.0           October
2036           0.23      2022.0         10.0       12.0           October
2037           0.23      2022.0         10.0       12.0           October
2038           0.23      2022.0         11.0       12.0          November
2039           0.23      2022.0         12.0       12.0          December

     Year_Month
0       2020-11
1       2020-11
2       2020-11
3       2020-11
4       2020-11
...         ...
2035    2022-10
2036    2022-10
2037    2022-10
2038    2022-11
2039    2022-12

[2040 rows x 21 columns]

Specific subsets of data are filtered, such as high-sales orders, loss-making orders, and category-specific orders. Aggregation techniques like group-by operations are applied to compute total sales by category, total profit by brand, and average quantity sold per state.

Purpose:

*   Identify high-performing and loss-making segments
*   Summarize data for business insights
*  Enable comparative analysis

In [ ]:
# Filtering
high_sales = df[df['Total_Sales'] > 10000]
loss_orders = df[df['Profit'] < 0]
electronics_orders = df[df['Category'] == 'Electronics']

print("High Sales:\n", high_sales.head())
print("\nLoss Orders:\n", loss_orders.head())
print("\nElectronics Orders:\n", electronics_orders.head())

High Sales:
    Order_Number State_Code   Customer_Name Order_Date      Status  \
1      139375.0         AP  Dannana Jhammi 2020-11-01   Delivered
2      139376.0         AS     Vipin Kumar 2020-11-01   Delivered
3      139377.0         BR   Ranjeet Kumar 2020-11-01   Delivered
4      139378.0         CG   Sajal Singhal 2020-11-01       Order
7      141921.0         MH     Adhir Samal 2020-03-04  Processing

                    Product      Category     Brand    Cost    Sales  ...  \
1      RYZEN 3rd gen. 3500            CPU     Intel  8500.0  11050.0  ...
2          2GB Graphic Card  Graphic Card    Nvidia  7000.0   9100.0  ...
3            16 GB DDR4 RAM           RAM     Hynix  6550.0   8515.0  ...
4  Standard ATX motherboard   MotherBoard  Gigabyte  7650.0   9945.0  ...
7          2GB Graphic Card       Monitor   Samsung  6550.0   8515.0  ...

   Total_Cost  Total_Sales  Assigned Supervisor  Profit  Profit_Margin  \
1     25500.0      33150.0         Roshan Kumar  7650.0           0.23
2     14000.0      18200.0          Aarvi Gupta  4200.0           0.23
3     19650.0      25545.0          Vijay Singh  5895.0           0.23
4     30600.0      39780.0           Aadil Khan  9180.0           0.23
7     10720.0      13936.0          Aarvi Gupta  3216.0           0.23

   Order_Year  Order_Month  Order_Day  Order_Month_Name Year_Month
1      2020.0         11.0        1.0          November    2020-11
2      2020.0         11.0        1.0          November    2020-11
3      2020.0         11.0        1.0          November    2020-11
4      2020.0         11.0        1.0          November    2020-11
7      2020.0          3.0        4.0             March    2020-03

[5 rows x 21 columns]

Loss Orders:
 Empty DataFrame
Columns: [Order_Number, State_Code, Customer_Name, Order_Date, Status, Product, Category, Brand, Cost, Sales, Quantity, Total_Cost, Total_Sales, Assigned Supervisor, Profit, Profit_Margin, Order_Year, Order_Month, Order_Day, Order_Month_Name, Year_Month]
Index: []

[0 rows x 21 columns]

Electronics Orders:
 Empty DataFrame
Columns: [Order_Number, State_Code, Customer_Name, Order_Date, Status, Product, Category, Brand, Cost, Sales, Quantity, Total_Cost, Total_Sales, Assigned Supervisor, Profit, Profit_Margin, Order_Year, Order_Month, Order_Day, Order_Month_Name, Year_Month]
Index: []

[0 rows x 21 columns]

In [ ]:
#  Aggregation
sales_by_category = df.groupby("Category", observed=False)['Total_Sales'].sum()
profit_by_brand = df.groupby("Brand", observed=False)['Profit'].sum()
avg_qty_by_state = df.groupby("State_Code", observed=False)['Quantity'].mean()

print("\nSales by Category:\n", sales_by_category)
print("\nProfit by Brand:\n", profit_by_brand)
print("\nAvg Quantity per State:\n", avg_qty_by_state)

Sales by Category:
 Category
CPU              7333950.0
Cabinet          1186770.0
Computer Case     828724.0
Graphic Card     5038150.0
HDD              4978350.0
Keyboard          535145.0
Monitor          9259016.0
MotherBoard        39780.0
Motherboard      1252953.0
Mouse            1618370.0
NIC               591994.0
Printer          1109667.0
RAM              1263457.0
SSD              4050800.0
Name: Total_Sales, dtype: float64

Profit by Brand:
 Brand
Acer                591105.0
Asus                273870.0
Dell               1341645.0
Gigabyte            550530.0
Hynix               503355.0
Intel              1692450.0
MSI                 304110.0
Nvidia             1162650.0
Samsung            1451541.0
Seagate             411000.0
Western Digital     737850.0
Name: Profit, dtype: float64

Avg Quantity per State:
 State_Code
AN    2.666667
AP    2.131579
AR    2.324324
AS    2.472222
BR    2.506579
CG    2.472222
CH    2.583333
DD    2.468750
DH    2.484848
DL    2.469697
GA    2.562500
GJ    2.477273
HP    2.866667
HR    2.228571
JH    2.457143
JK    2.575758
KA    2.083333
KL    2.416667
LD    2.941176
MH    2.434568
ML    2.411765
MN    2.636364
MP    2.648649
MZ    2.285714
NL    2.194444
OR    2.200000
PB    2.228571
PY    2.558824
RJ    2.638889
SK    2.333333
TN    2.287671
TR    2.428571
UK    2.411765
UP    2.647059
WB    2.657143
Name: Quantity, dtype: float64